### ISSUE TITLE
Support for editing

### ISSUE THREAD

**Issue by ArekPiekarz** [tarkah/iced_table#1]
The example in this repository shows only how to create a read-only table. Does this crate support editing of the table contents by the user? For example, when a user clicks a cell, it should change into an editable widget (like a text input) and after the user is done (for example, presses Enter), it should revert to "read-only" mode with updated content.

**Comment by tarkah** [comment]
Absolutely, each cell is an Element so you can do whatever you want!

**Comment by ZegCricket** [comment]
I'm having trouble implementing the example with text inputs instead of text labels, because I can't create a message that "knows" which cell is being modified in order to modify the correspondent value of the array (I don't know if it is possible to pass the col_index to the message). I'm new to Rust and Iced, so I apologize if this is a simple question. Could someone show the example that is in the repository with the necessary changes?

**Comment by mschnell1** [comment]
Yep in iced_widget helpers.rs, the fn checkbox is defind to acceopt only messages that feature a boolean argument. `f: impl Fn(bool) -> Message + 'a,`
I'll do some more research...
Such as askinh in the iced_widget repository

**Comment by tarkah** [comment]
impl Fn is a closure, meaning you can pass in state when defining the closure. You aren't limited to only working with bool. As long as the state passed in is lifetime 'a, all is fine. When in doubt, clone and move state into the closure to please the borrow checker.

**Comment by mschnell1** [comment]
Thanks a lot for commenting. 
This is the first time I see an enum element passed to a function as a impl Fn. I did not suspect that such is possible, even though it perfectly makes sense logically and syntactically. Hence I need to learn more about this. 
In fact what I would like is to assign an ID (i32) to each (e.g.) created (in a loop) and pass this if with the message. E.g. by defining 
```
enum Messages {
....
  checkbox_message(bool, i32) 
....
}
```

**Comment by tarkah** [comment]
Here's some pseudo code:

```rs
for (i, item) in items.iter().enumerate() {

  // ....

  checkbox(.., |checked| Message::Checkbox(i, checked))
}
```

**Comment by mschnell1** [comment]
Great !
looking forward to testing this tomorrow...

**Comment by mschnell1** [comment]
Seemingly calling the function with an enum element secretly constructs a closure for setting the value. But it also can be done explicitly.

I assume this means the first element of this message is set by this code, and then  the second element is updated by the widget's code via calling the closure.

While researching, I found that the appropriate parameter with **button** is constructed differently.
Lets see where I get...

I am doing  a simple example with vectors of checkboxes and buttons.
Maybe you might want to include those with your example packages...

**Comment by mschnell1** [comment]
@tarkah 
Directly using the message closure with the checkbox  works perfectly. 
I could create a vector of checkboxes, each with their own ID, their own text, their own `checked` state and their own functionality.

I also could create a vector of buttons, each with their own texts, 
Now trying to provide them each a dedicated functionality. That would be easy using the same ID and closure trick as with the checkboxes. 
But unfortunatly the `button()` view function seemingly does not provide a closure for passing the message to be sent, but the `on_press()` fuction, seems to take kust a message without attributes. 

What to do?

**Comment by mschnell1** [comment]
this works:
```
            let message = move |checked| Message::CheckBoxInVecToggled(id, checked);
            let item = checkbox(label, was_checked, message // needs closure to pass id to the message

            let message = Message::ButtonPressed;
            let item = button(label).on_press(message);
```

I tested: 
```
            let message = move || Message::ButtonInVecPressed(id);
            let item = button(label).on_press(message); // Todo: id into Message
            children.push(item);
```
This results in an error.  
`expected "Element<'_, Message, Renderer<Theme>>", found "Element<'_, {closure@main.rs:153:27}, _>"`

Seemingly an enum element can be passed to a function that expects an `impl Fn(...)`,  but a closure can't be passed to a function that expects an enum element. 

It would be great if the `button()` code could be updated to adhere to the same paradigm as `checkbox()`, `radio()`, `toggler()`, `slider()`, `vertical_slider()`, `pick_list()`, and `combo_box()`, 

Or is ther another appropriate way ?

**Comment by mschnell1** [comment]
@tarkah
I found that `Radio` features an internal mechanism for providing messages with an id. 

Nice but in fact the closure method you suggested (without the additional "value" ßparameter) to me seems by for more appropriate and versatile.

**Comment by tarkah** [comment]
Nice progress! For button, you just encode the Id to the enum variant. There's no need for a closure:

```rs
enum Message {
  ButtonPressed(usize),
}

// ..

button(..).on_press(Message::ButtonPressed(index))
```

**Comment by mschnell1** [comment]
Great. I'm looking forward to try this ASAP. 
(And find out how it's possible that `on_press()` can accept different message types without being a generic itself.)
Grrr. Yet another method to distinguish the members of the  "column" vector.
(Anyway, IMHO, a common identification method for all current and future / native and custom widgets would make a lot sense.)

**Comment by mschnell1** [comment]
@tarkah 
Of course `button(..).on_press(Message::ButtonPressed(index))` does work as expected. Thanks for Your help !

I now do have a nice little example program "`iced-example-widgets_in_vec`", that IMHO could be helpful to users, and might be provided with the other examples in the `iced` crate. Can I upload it somewhere to provide it for that use ? 

OTOH, I have the impression that it demonstrates that  passing an ID with the message needs to be handled completely differently with `button()`, `checkbox()`, and `radio()`, which is not really desirable. I have the impression that using a builder pattern (such as `button().on_press()` for all the different widgets to be provided with the message to be fired, might be a sensible modification the iced library might see in the near future and hence my example might be obsolete. 
Thanks for listening !
(Would it make sense to re-post the result as an issue in the iced-rs repository ?)

**Comment by mschnell1** [comment]
Ranting on ....

Is it possible to do a function that that would take an element of an enum (here a dedicated message) and work with same later by  setting one (e.g. the first) of it's attributes (of a type known to that function), while leaving the other arguments (of unknown type) as they were given ? 
This is essentially, what is done by the closure used with `checkbox()`, but in a more user friendly way as done with `button()` - which does accept messages with unknown arguments, but of course does not modify any of them. 

A (IMHO) super cool (maybe impossible) implementation (based on building pattern) would allow something like this:  
`let item = checkbox_builder(label).is_checked(true).on_press(Message::checkboxes(_, id));`
( `.is_checked(false)` would be default and could be omitted ) 

Such paradigm could be used with all possible widgets. 

Or even something like this might make sense:
 ```
let item = widget_builder()
    .widget_type(WidgetType::checkbox)
    .label("Hello")
    .is_checked(true)
    .on_press(Message::checkboxes(_, id));
```
With that any widget could have default attributes that could be overridden when building. 

P.S.: if Rust does not allow the kind of parameter transfer I'd like to see, maybe you could do something like 
`    .on_press!(Message::checkboxes(_, id)) `
and have a nice macro do the complicated stuff, constructing a closure with all ` _ ` arguments converted to parameters into the closure.

What do you think ?
Michael (determined to reading up on Rust macros....)

**Comment by tarkah** [comment]
New example demonstrates how to edit via the table using application state:

https://github.com/tarkah/iced_table/blob/master/example/src/main.rs

**Comment by mschnell1** [comment]
Excellent !
Thanks a lot !

**Comment by mschnell1** [comment]
Hi @tarkah again !
Due to all your help I am making a lot of progress. 
But I am stuck at a new roadblock. 
I want to implement a context menu for a cell in the table. 
I see that menus are implemented with iced, but I don't find any example, only unresolved questions. 
Is there any hope for my endeavor ? 
Thanks again !

**Comment by tarkah** [comment]
We've implemented a context menu in halloy, you can reference that 

https://github.com/squidowl/halloy

**Comment by mschnell1** [comment]
@tarkah 
Thanks a lot.
Of course I could clone the project and run it (don't see a menu as that seems to need connecting to an appropriate server)

I do see the code for the context menu. But same is by far too complex for me to analyze and understand and partially integrate in my testing project :(

**Comment by mschnell1** [comment]
e.g. I am confused by there being another `src` dir and `cargo.toml `below `data`. 

I am aware of using dirs for modules, but using packages within a package is beyond my scope yet. 
I do see `path = "data" ` is mentioned in the dependencies in the main `cargo.toml` file, and hence it can be accessed. But what are the implications ? Is this necessary for doing decent context menus (like dedicated crates seem to be necessary for doing procedural macros), or is this done for other reasons ? (Seems like I need to get up to speed with workspaces ....)

Moreover three `themes.rs` files seem to be involved. One in `src`, one in, `data/src` and one in the external `iced` crate. I am lost with this ambiguity .

(Sorry for being a PITA. but there seems to be no understandable documentation for using `menu` in `iced` :( )

**Comment by mschnell1** [comment]
Ahhh
Seemingly the server` irc.libera.chat` is accessible from my home (not being behind a firewall as my office in the company)  I can see the context menu in action :) ....

I see that the GUI is perfectly versatile.
GREAT  !
