### ISSUE TITLE
accessing states in Column::cell()

### ISSUE THREAD

**Issue by mschnell1** [tarkah/iced_table#3]
maybe this is in line with issue #2 

Thanks for this crate that comes very handy for my work. 

I am new to iced (and GUI in Rust) but already did several Rust projects and took a deep look into the workings of the gui librariy in Free Pascal / Lazarus. 

I found that (in the example provided) I easily can change the content of a cell by other widgets instead of "text" such as a button or a checkbox. Supposedly I will need to place several widgets in a cell, but I think that will be doable, as well. 

But a very simple thing I could not find out. In the original example I tried to have the text of a single cell be modified according to a state in the application, that can be modified by means outside of the table (e.g. one of the checkboxes in the example). Hence in the "Column::cell" function I need access to that data. Of course a global struct might be usable, but I feel this is not decent Rust programming. With Non Rust GUI libraries there is a global "Application" reference and other global stuff usable in such situations. But when doing rust, a decent safe transfer of such a reference into the function would be necessary. 

How is this supposed to be done ? 
Would I need to modify the source of the "iced_table" lib.rs to e.g. provide cell() with additional arguments ?

**Comment by tarkah** [comment]
Whatever you implement table::Column on can hold the application state you desire, passed in during view.

In the example, Letter is application state that's passed in. But this can be anything you want.

**Comment by mschnell1** [comment]
Thanks a lot for answering. (Right now I am not at the office) 
In fact ` table::Column `is not my work but part of the iced_table crate.Of course if necessary I can create a new version of same.
I'll try to proceed, when I am back in the office...
Thanks again

**Comment by mschnell1** [comment]
I found I can do a struct (e.g. `Button{}`) to hold the state (e.g. `checked`) of the widget, and create a vec of those structs in (or deeply below) the application struct. Now the view function (e.g. `button()` ) can see that state, and as well the `update() `as  the business code can access the state via the application struct. Maybe this is all what is necessary in the end.
(Now finding out how to trigger a redraw if the business code (asynchronously) modified a visible state.... . Seemingly after `update()` everything is redrawn, anyway)

**Comment by mschnell1** [comment]
@tarkah 
_"Whatever you implement table::Column on can hold the application state you desire, passed in during view.
In the example, Letter is application state that's passed in. But this can be anything you want."_

Yep. 
I easily was able to use a struct instead of an enum in the columns struct (which I renamend to `ColumnSpecification `). 

Now trying to find out how to pass a reference to a general application state struct (or part of same) through  that channel. (while making the borrough checker happy....)

In the end, my intention is to have a container with multiple widgets in each Cell of the table, each such widget showing an appriopriate "state" of the application, and each of same being able to fire a message that is denoting the cell (and appropriate additional states) to have the application work on this. 

Do you have more tips for me ? 
Thanks a lit !

**Comment by mschnell1** [comment]
@tarkah 
Sorry for continuing being a PITA, but I don't get this concept right.
I introduced a new element in the `ColumnSpecification ` stuct (renamed from just `column` in the `table`  example ). 
Same is supposed to provide a reference to the "**Business** state" of the application to allow the widgets drawn in the `cell()` function (that seemingly is called in `view()` fom the infrastructure ) to be displayed according to that state, as `cell() ` features the `ColumnSpecification `as the `self` parameter.
(Currently working but not desirable (not "idomatic", using `unsafe` ): this application state is a defined globally:
```
static mut APPLICATION: Business = Business {
    test: false,
    _phantom_data: std::marker::PhantomData {},
};
```
 )


**Problem**: 
The colums are constructed in the 
```
impl Default for App<'_> {
    fn default() -> Self {
.....
```
function. 
Hence here I would need to provide a reference to the `Business`  implementation. 
`default()` seemingly is called by 
```
fn main() {
    App::run(Default::default()).unwrap()
}
```
`run()` does not seem to allow to be fed with additional parameters. 
Question: Where / how can I create the "Business" (Application state) instance before `default ` is called and how to set the appropriate reference in the columns ? 

In `App::default()` I e.g. tried: 
```
               for mut c in &mut t.columns {
                   let mut b: Business<'static> = Business::new();
                   b.test = true;
                   c.business.replace(&b);
               }
```
But for `&b` I get: "borrowed value does not live long enough". (Sorry for not yet being decemntly up top speed with rust livetimes)

Thank for any pointers ...
-Michael

**Comment by mschnell1** [comment]
**Ranting on ......**
I found a way to do this by wrapping the `business `element in `ColumnSpecification` in a reference counting Pointer     `business: Option<Rc<RefCell<Business<'l>>>>,`  
(As `iced `can be multithreadded, I supposedly should use `Arc`). 
The code now seems hellishly unnecessary complex - supposedly because I diod npt manage to do the perfect "lifetime aware" code, but I got rid of the `unsafe `stuff.
What do you think ?

**Comment by tarkah** [comment]
@mschnell1 I've updated the example to hopefully show how to better use application state in the table. I've used a checkbox, button & text_input to hopefully demonstrate this better:

https://github.com/tarkah/iced_table/blob/master/example/src/main.rs

Hope this helps!

**Comment by mschnell1** [comment]
GREAT !
This already does look similar to what Iam intendeing to do . 
I managed to do a "business" struct for application states and make same accessibkle n the view (cell) function to allow for showing "global" stuff in any widget. Herer I did not decently consider the Row struct. Supposedly I should rework regarding that,
