### ISSUE TITLE
Support for viewport clipping?

### ISSUE THREAD

**Issue by nednoodlehead** [tarkah/iced_table#4]
It would be great if the table was able to handle 1000's of items without lagging by only rendering what is visible on the viewport. I do not know enough about iced to make a pr, but I do know that the [scrollable](https://github.com/iced-rs/iced/blob/111c8bfa7965cad8fe7253c8601e620b8582eaaf/widget/src/scrollable.rs#L990) supports this.

Simple way to test is to replace [line 51](https://github.com/tarkah/iced_table/blob/bf1c2414ca75766905889984d71c8f9002b953ad/example/src/main.rs#L51C13-L51C56) in the example repo to:
```rust
rows: (0..10000).map(Row::generate).collect(),
```

**Comment by tarkah** [comment]
It is clipped via use of scrollable, but layout still has a cost. Did you  run in `--release` mode?

**Comment by nednoodlehead** [comment]
Yeah, just tested release with 10k rows. Takes about a full second to register scrolls, do you have different results?

edit: 10k rows has an average memory use of 200mb, 100 rows has about 60-70mb. (Win11, --release mode)

**Comment by tarkah** [comment]
Yeah it's slow, this really just comes down to `layout` which can't be avoided (how else can you determine the full size of the scrollable for computing scrollbar position?). And text has a huge layout cost.

I believe there's some optimizations coming down the pipeline for global text caching that may eventually help here (our example uses the same few instances of text).

But in general, having a table of 10k elements is probably not wise. At that point, implementing some pagination buttons and limiting how many records get passed into the table is probably the best move.

**Comment by nednoodlehead** [comment]
I see your point, but I'm developing this for an application that you can view a database ([here](https://github.com/nednoodlehead/punge), similar to in widget functionality to [DB browser](https://github.com/sqlitebrowser/sqlitebrowser)). So I'd like my users to be able to just scroll endlessly, without worrying about pages or anything.

I did find a small 'fix' that improves cpu performance by ~2-3x when scrolling with the scrollbar on a table with 1500 rows. I'm not sure if it is related to my slight modifications of the project (just changing column amount -> 3 and making all widgets text) , but removing it seems to not affect functionality whatsoever.

In [example/src/main.rs, line 84](https://github.com/tarkah/iced_table/blob/7af2b1f6ad318bf43190904aead9046f0b4cff1d/example/src/main.rs#L84): Removing the entire return statement.

**Comment by nednoodlehead** [comment]
Not much to really do from this repo, ig its an iced thing.
