### ISSUE TITLE
when might we see a version that works with the current iced head

### ISSUE THREAD

**Issue by pm100** [tarkah/iced_table#5]
Many, many changes in iced since 0,10, this code doesnt compile anymore .

**Comment by tarkah** [comment]
I've updated `master` to point to iced `master`. I won't make a release until iced releases `0.12`

**Comment by pm100** [comment]
@tarkah thanks, i tried to make the same changes myself, but am an iced novice so I wimped out :-(

**Comment by tarkah** [comment]
Np! Thanks for opening the ticket, it's easy to lose sight of these updates.

And yeah, it's a bit of work since the Iced API can change so much between releases. This one had a few tricky things!
