### ISSUE TITLE
Table is not compatible witth the current iced "0.12"

### ISSUE THREAD

**Issue by mschnell1** [tarkah/iced_table#7]
Should it  ?

**Comment by mschnell1** [comment]
OOOps. 
Seems already in the works due to #5

**Comment by mschnell1** [comment]
Retested .... Definitively does not work for me on iced "0.12"

**Comment by tarkah** [comment]
I need to update and cut a new release. I'll work on it in the next few days

**Comment by tarkah** [comment]
I've updated and published a new release. I've aligned this crates version with iced, so 0.12

**Comment by mschnell1** [comment]
GREAT !
Testing tomorrow.....
