### ISSUE TITLE
The main.rs in the example does not work

### ISSUE THREAD

**Issue by soucosmo** [tarkah/iced_table#8]
When running the main.rs example, I get an error "**error[E0432]: unresolved import `iced::widget::responsive`**"

My console:
```
error[E0432]: unresolved import `iced::widget::responsive`
 --> src/main.rs:4:71
  |
4 |     button, checkbox, column, container, horizontal_space, pick_list, responsive, scrollable, text,
  |                                                                       ^^^^^^^^^^ no `responsive` in `widget`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `costv` (bin "project") due to 1 previous error
```
[Archive (1).zip](https://github.com/tarkah/iced_table/files/14782835/Archive.1.zip)

**Comment by tarkah** [comment]
I cannot reproduce. Make sure you do a `cargo clean` before building an `cargo run -p example` from the root of the repo.
